name: Payment Gateway Stress Test

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  run-k6-stress:
    name: Execute k6 Load Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Run k6 Load Test Routine
        uses: k6io/action@v0.2.0
        with:
          filename: payment_stress_test.js   # This forces it to target your wallet script
